class BatteryEKF(ExtendedKalmanFilter):
  def __init__(self, battery, initial_voltage: array) -> NONE: ... #is battery here the class Battery?
  def soc(self): -> array: ...
  def step(self, dt: int | float, i_in: float, measured_v: float) -> NONE: ...
