from battlib.battery import Battery


class BatteryCC: 
    def __init__(self, battery: Battery, initial_soc: float) -> None: ...
    @property
    def soc(self) -> float: ...
    def step(self, i_in: float, dt: float, measured_v: float | None = None) -> None: ...
