from filterpy.kalman import ExtendedKalmanFilter  # type: ignore[import]
from battlib.battery import Battery

class BatteryEKF(ExtendedKalmanFilter):  # type: ignore[misc]
    def __init__(self, battery: Battery, initial_voltage: float) -> None: ...
    @property
    def soc(self) -> float: ...
    def step(self, dt: int | float, i_in: float, measured_v: float) -> None: ...
